
### DATABASE ###
server:
  port: 8087
##spring.mvc.pathmatch.matching-strategy=ant_path_matcher#
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
  application:
    name: AUTH-SERVICE
  config:
    import: configserver:http://localhost:9296