server:
  port: 9090
spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri:
            lb://ORDER-SERVICE
          predicates:
            - Path=/Order/**
          filters:
            - AutenticationFilter
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack

        - id: AUTH-SERVICE
          uri:
            lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: AUTH-SERVICE
                fallbackuri: forward:/authServiceFallBack
        - id: PRODUCT-SERVICE
          uri:
            lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - AutenticationFilter
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack


        - id: PAYMENT-SERVICE
          uri:
            lb://PAYMENT-SERVICE
          predicates:
            - Path=/Payment/**
          filters:
            - AutenticationFilter
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack


